config/routes.rb
Rails.application.routes.draw do
  get 'balances/index'
  resources :payments, except: %i[ new create]
  resources :products
  resources :customers do 
   resources :loans, only: %i[ new create]
   resources :payments, only: %i[ new create]
  end
 
  resources :loans, except: %i[ new create] do
    collection do  
      get 'form_product', to: 'loans#form_product', as: 'add_products'
    end
  end




  

 
  #Devise 
  devise_for :admins do 
   get '/admins/sign_out', to: 'devise/sessions#destroy', as:'add_logout'
  end 
  authenticate :admin do
   root to: "customers#index"
  end
end


app/models/customer.rb
class Customer < ApplicationRecord
  has_many :payments
  has_many :loans
  validates :name, presence: true


  def total_payments
   payments.pluck(:balance_paid).sum
  end

  def total_loans
    loans.pluck(:total_loan).sum
  end

  def balance
    total_loans - total_payments
  end

end



app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: %i[ index]    

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
    @customers = @customers.where("name ilike ?", "%#{params[:q]}%") if params[:q]
  end

  
  def show
    @customer_data = @customer.loans.select("loans.created_at,SUM(loans.total_loan)").where('created_at > ?', Date.today.beginning_of_month - 1.year).group_by_month('loans.created_at', format: "%b %Y").sum(:total_loan)
  end

  
  def new
    @customer = Customer.new
  end


  def edit
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :last_name, :address, :telephone)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<tr>
  <td class="text-center"><%= customer.name %></td>
  <td class="text-center"><%= customer.last_name %></td>
  <td class="text-center"><%= customer.address %></td>
  <td class="text-center"><%= customer.telephone %></td>
  <td><button class="btn-sm"><%= link_to 'Crear Nuevo Préstamo', new_customer_loan_path(customer), id: "new-loan"%></button></td>
  <td><button class="btn-sm"><%= link_to 'Crear Nuevo Abono', new_customer_payment_path(customer), id: "new-payment" %></button></td>
  <td class="text-center"><%= link_to 'Detalle', customer %></td>
  <!--<td class="text-center"><%= link_to 'Editar', edit_customer_path(customer) %></td>
  <td class="text-center"><%= link_to 'Eliminar', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
</tr>


app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<body class="bg-form">
  <div id="layoutAuthentication">
      <div id="layoutAuthentication_content">
          <main>
              <div class="container">
                  <div class="row justify-content-center">
                      <div class="col-lg-7">
                          <div class="card shadow-lg border-0 rounded-lg mt-5">
                              <div class="card-header"><%= image_tag "logo_carniceria.png", width: "200px", heigth: "800px", class: "img" %></div>
                              <div class="card-body">
                                  <form>
                                    <div class="form-row">
                                      <div class="col-md-6">
                                          <div class="form-group">
                                            <label class="medium mb-1" for="inputFirstName">Nombre</label>
                                            <%= form.text_field :name, class: 'form-control py-4', placeholder: 'Primer Nombre' %>
                                          </div>
                                        </div>  
                                        <div class="col-md-6">
                                          <div class="form-group">
                                            <label class="medium mb-1" for="inputLastName">Primer Apellido</label>
                                            <%= form.text_field :last_name, class: 'form-control py-4', placeholder: 'Apellido' %>
                                          </div>
                                        </div>
                                        </div>
                                        <div class="form-group">
                                          <label class="medium mb-1" for="inputEmailAddress">Dirección</label>
                                          <%= form.text_field :address, class: 'form-control py-4', placeholder: 'Dirección' %>
                                        </div>
                                        <div class="form-row">
                                          <div class="col-md-6">
                                            <div class="form-group">
                                              <label class="medium mb-1" for="inputPassword">Telefóno</label>
                                              <%= form.text_field :telephone, class: 'form-control py-4', placeholder: 'Telefóno' %>
                                            </div>
                                          </div>
                                        </div>
                                          <%= form.submit class: "btn btn mt-4 mb-0 text-white", id:'btn-new' %>
                                          <% end %>
                                      <button type="button" id="btn-s"><%= link_to 'Mostrar', @customer, id: "btn-color" %></button> 
                                      <button type='button'><%= link_to 'Regresar', customers_path, id: "btn-color" %></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
      </div>
    </div> 
</body>  


  

app/views/customers/edit.html.erb
<%= render 'form', customer: @customer %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<section class="container mt-0 mb-5">
  <%= image_tag "logo_carniceria.png", class:"img-fluid", width: 970 %>
</section>

<section class="container">
  <form class="d-inline-flex my-lg-2 mt-5" id="search">
    <input class="form-control mr-sm-4" type="search" placeholder="Buscar clientes" aria-label="Search" name="q">
  </form>
  <button class="btn btn" id="client"><%= link_to 'Crear Nuevo Cliente', new_customer_path, id:"color" %></button>
  
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="80%" cellspacing="0">
        <thead>
          <tr>
            <th class="text-center text-white">Nombre</th>
            <th class="text-center text-white">Apellido</th>
            <th class="text-center text-white">Dirección</th>
            <th class="text-center text-white">Teléfono</th>
            <th class="text-center text-white">Nuevo Prestámo</th>
            <th class="text-center text-white">Nuevo abono</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody id="customers">
          <%= render @customers %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/customers/index.js.erb
$('#customers').html('<%= j render @customers %>');

app/views/customers/new.html.erb
<%= render 'form', customer: @customer %>
<br>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<button type="button" class="btn btn text-white" id="customer_edit">Editar cliente</button>
<section>
  <div class="card" style="width: 18rem;" id="card_customer">
    <div class="card-body head">
      <h5 class="card-title text-white text-center">Saldo del Cliente</h5>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Nombre: 
      <%= @customer.name %> <%= @customer.last_name %>
      </li>
      <li class="list-group-item">Saldo pendiente:
        <%= @customer.balance %>
      </li>
      <div class="card-body">
        <button id="space-a"><%= link_to 'Abonar', new_customer_payment_path(@customer), id: "color-font" %></button> 
        <button><%= link_to 'Regresar', customers_path, id: "color-font" %></button> 
      </div>    
    </ul>
  </div>
</section>

<div class="card mx-auto" id="show_customer" style="width: 18rem;">
  <div class="card-body head">
    <h5 class="card-title text-white text-center">Datos del Cliente</h5>
  </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Nombre: 
      <%= @customer.name %>
      </li>
      <li class="list-group-item">Apellido:
        <%= @customer.last_name %>
      </li>
      <li class="list-group-item">Dirección:
        <%= @customer.address %>
      </li>
      <li class="list-group-item">Télefono:
        <%= @customer.telephone %>
      </li>   
    </ul>
    <div class="card-body">
      <button id="space-e"><%= link_to 'Editar', edit_customer_path(@customer), id: "btn-c" %></button> 
      <button><%= link_to 'Eliminar', @customer, id: "btn-c", method: :delete, data: { confirm: 'Are you sure?' } %></button>
    </div>
</div> 
  
<div class="mt-5">
  <h2 class="mt-5 mb-4">Ventas Mensuales</h2>
  <%= line_chart @customer_data %>
</div>  