config/routes.rb
Rails.application.routes.draw do
  get 'balances/index'
  resources :payments, except: %i[ new create]
  resources :products
  resources :customers do 
   resources :loans, only: %i[ new create]
   resources :payments, only: %i[ new create]
  end
 
  resources :loans, except: %i[ new create] do
    collection do  
      get 'form_product', to: 'loans#form_product', as: 'add_products'
    end
  end




  

 
  #Devise 
  devise_for :admins do 
   get '/admins/sign_out', to: 'devise/sessions#destroy', as:'add_logout'
  end 
  authenticate :admin do
   root to: "customers#index"
  end
end


app/models/loan.rb
class Loan < ApplicationRecord
  before_save :set_prices
  belongs_to :customer
  has_many :loan_products, dependent: :destroy
  has_many :products, through: :loan_products
  accepts_nested_attributes_for :loan_products, reject_if: :all_blank, allow_destroy: true


  private

  def set_prices
    self.loan_products.each do |product|
      product.product_price = product.product.price
    end
    self.total_loan = self.loan_products.map{|p| p.product_quantity * p.product_price}.sum   
  end
end


app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: %i[index]
  before_action :set_customer, only: %i[ new create]  
  
  def index
    @products = Product.includes([:customer]).all
    @customers = Customer.includes([:product]).all
    @loans = params[:q] ? Customer.find_by('name ilike ?', "%#{params[:q]}%").loans : Loan.includes([:customer]).all
  end
  
  def edit  
    @customers = Customer.pluck(:name, :id) 
    @products = Product.pluck(:name_product, :id) 
  end

  def show
    @loans = Loan.all
    @products = Product.all
    @customers = Customer.all 
  end

  def new 
    @customers = Customer.pluck(:name, :id) 
    @loan = Loan.new 
    @products = Product.pluck(:name_product, :id)
    @loan.loan_products.build 
  end
  
  def create
    @loan = Loan.new(loan_params.merge(customer: @customer))
    #@products = Product.pluck(:name_product, :id)
   
    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: "loan was successfully created." }
        format.json { render :show, status: :created, location: @loan }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: "loan was successfully updated." }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy 
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def form_product
    @products = Product.pluck(:name_product, :id)
    @loan = Loan.new
    @loan.loan_products.build
    respond_to do |format|
      format.js
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_loan
    @loan = Loan.find(params[:id])
  end

  def set_customer
   @customer = Customer.find(params[:customer_id])
  end
  # Only allow a list of trusted parameters through.
  def loan_params
    params.require(:loan).permit(:customer_id, 
   loan_products_attributes: [:id, :product_quantity, :product_price, :loan_id, :product_id])
  end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<div class="container">
  <%= form_with(model: [@customer, loan]) do |form| %>
    <% if @customer.present? %>
      <p><strong>Cliente:</strong>&nbsp;<%= @customer.name %>&nbsp;<%= @customer.last_name %></p>
    <% elsif%> 
      <p><strong>Cliente:</strong>&nbsp;<%= @loan.customer.name %>&nbsp;<%= @loan.customer.last_name %></p>
    <% end %>
    <%= form.fields_for :loan_products do |loan_product| %>
          <div id="product_fields">
            <div>
              <div class="field">
                <%= loan_product.label :product_id %>
                <%= loan_product.select :product_id, @products, prompt: "Seleccione un producto" %>
              </div>
              <div class="field">
                <%= loan_product.label :product_quantity %>
                <%= loan_product.text_field :product_quantity %>
              </div>
            </div>
          </div>     
    <%end%>
        <br>
        <%= link_to "Añadir más productos", add_products_loans_path, id: "add_product", remote: true %>                  
        <br>
        <%= form.submit class: 'actions btn btn', id: "color"%>
          <button id="btn-b"><%= link_to 'Regresar', customers_path, id: "color-back" %></button>
          <button id="btn-s"><%= link_to 'Mostrar', @loan, id: "color-back" %></button>
       <% end %>
</div>

app/views/loans/_loan.html.erb
 <tr>
    <td class="text-center"><%=loan.customer.name%></td>
    <td class="text-center"><%=loan.customer.last_name%></td>
    <td class="text-center"><%=loan.total_loan%></td>
    <td class="text-center"><%=loan.created_at%></td>
    <td class="text-center"><%= link_to 'Show', loan %></td>
    <td class="text-center"><%= link_to 'Edit', edit_loan_path(loan) %></td>
    <td class="text-center"><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
</tr>

app/views/loans/edit.html.erb
<h2 class="mb-5">Editar Préstamo</h2>
<%= render 'form', loan: @loan %>

app/views/loans/form_product.js.erb
function fields() {
  var num = document.querySelectorAll('#product_fields > div').length
  var html = `<div>
      <div class="field">
          <label for="loan_loan_products_attributes_0_product_id">Product</label>
          <%= select_tag :product_id, options_for_select(@products), name: 'loan[loan_products_attributes][0][product_id]', prompt: "Seleccione un producto" %>
      </div>
      <div class="field">
          <label for="loan_loan_products_attributes_0_product_quantity">Product quantity</label>
          <input type="text" value="1" name="loan[loan_products_attributes][0][product_quantity]" id="loan_loan_products_attributes_0_product_quantity">
      </div>
  </div>`

  return html.split('0').join(num)
}

$('#product_fields').append(fields())

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<section class="container mt-0 mb-5">
  <%= image_tag "logo_carniceria.png", class:"img-fluid", width: 950 %>
</section>

<section class="container mb-3 mt-2">
<h2 class="mb-4">Registro de Préstamos</h2>
  <form class="d-inline-flex my-lg-2" id="search">
    <input class="form-control mr-sm-4" type="search" placeholder="Buscar préstamos" aria-label="Search" name="q">
  </form>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
            <th class="text-center text-white">Nombre</th>
            <th class="text-center text-white">Apellido</th>
            <th class="text-center text-white">Total de préstamo</th>
            <th class="text-center text-white">Fecha</th>
            <th colspan="3"></th>
            </tr>
          </thead>

          <tbody id="loans">
            <%= render @loans%>
          </tbody>
        </table>
      </div>
    </div>
</section>

app/views/loans/index.js.erb
$('#loans').html('<%= j render @loans %>');

app/views/loans/new.html.erb
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg">
                          <div class="card-header"><%= image_tag "logo_carniceria.png", width: "200px", heigth: "800px", class: "img" %></div>
                            <div class="card-body">
                              <%= render 'form', loan: @loan %>
                          </div>
                        </div>             
                    </div>
                </div>
            </div>
        </main>
    </div> 
</div>  

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<section class="container">
  <div class="card mx-auto" style="width: 20rem;">
    <div class="card-body head">
      <h5 class="card-title styles">Detalle del Préstamo</h5>
    </div>
      <p class="p-head">Nombre de Cliente:</p>
        <p class="p-content"><%= @loan.customer.name %></p>

      <p class="p-head">Productos:</p>
        <% @loan.loan_products.each do |loan|%>
        <p class="p-content"><%=loan.product.name_product%></p>
        <strong><p class="p-content"><%=loan.product.price%></p></strong> 
        <% end %>
    
      <p class="p-head">Total de préstamo:</p>
        <p class="p-content"><%= @loan.total_loan %></p>
        <%= link_to "Regresar", customers_path, id: "style" %>
  </div>  
</section>
