config/routes.rb
Rails.application.routes.draw do
  get 'balances/index'
  resources :payments, except: %i[ new create]
  resources :products
  resources :customers do 
   resources :loans, only: %i[ new create]
   resources :payments, only: %i[ new create]
  end
 
  resources :loans, except: %i[ new create] do
    collection do  
      get 'form_product', to: 'loans#form_product', as: 'add_products'
    end
  end




  

 
  #Devise 
  devise_for :admins do 
   get '/admins/sign_out', to: 'devise/sessions#destroy', as:'add_logout'
  end 
  authenticate :admin do
   root to: "customers#index"
  end
end


app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]
  before_action :set_customer, only: %i[ new create]

  # GET /payments or /payments.json
  def index
    @payments = Payment.includes([:customer]).all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @customers = Customer.all
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
    @customers = Customer.all
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params.merge(customer: @customer))
    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    def set_customer
      @customer = Customer.find(params[:customer_id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:balance_paid, :customer_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model:  [@customer, payment]) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>
      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--Tipo de Cambio CR-->
<div class="text-right">
    <table class="table table-sm table-borderless d-flex align-items-end flex-column bd-highlight">
      <thead class="divisas"> 
        <tr>
          <th class="text-white">Compra</th>
          <th class="text-white">Venta</th>
          <th class="text-white">Fecha</th>
        </tr>
      </thead>
      <tbody class="d-flex align-items-end flex-column bd-highlight">
        <tr>
          <td class="style" id="compra"></td>
          <td class="style" id="venta"></td>
          <td class="style" id="fecha"></td>
        </tr>
      </tbody>
    </table>
</div>
 
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                          <div class="card-header"><%= image_tag "logo_carniceria.png", width: "200px", heigth: "800px", class: "img" %></div>
                            <div class="card-body">
                              <form>
                                <% if @customer.present? %>
                                    <p><strong>Cliente:</strong>&nbsp;<%= @customer.name %>&nbsp;<%= @customer.last_name %></p>
                                    <p><strong>Saldo pendiente:</strong>&nbsp;<%= @customer.balance%></p>
                                  <% elsif%> 
                                    <p><strong>Cliente:</strong>&nbsp;<%= @payment.customer.name %>&nbsp;<%= @payment.customer.last_name %></p>
                                  <% end %>
                                  <div class="form-group">           
                                    <label class="medium mb-1" for="inputPassword">Abono</label>
                                    <%= form.text_field :balance_paid, class:'form-control py-4 mb-1', placeholder: 'Cantidad a abonar' %>
                                  </div>
                                  <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <%= form.submit class: "actions btn btn", id: "create", data: {disable_with: 'submitting...'} %> 
                                    <button type="button"id="btn"><%= link_to 'Regresar', customers_path, id: "color-back" %></button>
                                  </div>
                                  <% end %>
                              </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

app/views/payments/edit.html.erb
<h2 class="text-center">Editar Abono</h2>

<%= render 'form', payment: @payment %>

<!--<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>-->

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<section class="container mb-5">
  <%= image_tag "logo_carniceria.png", class:"img-fluid", width: 950 %>
</section>

<section class="container mt-4">
  <h2 class="mb-4">Registro de Abonos</h2>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th class="text-white text-center">Nombre del Cliente</th>
            <th class="text-white text-center">Apellido</th>
            <th class="text-white text-center">Saldo Abonado</th>  
            <th class="text-white text-center">Fecha de Abono</th>  
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @payments.each do |payment| %>
            <tr>
              <td class="text-center"><%= payment.customer.name %></td>
              <td class="text-center"><%= payment.customer.last_name %></td>
              <td class="text-center"><%= payment.balance_paid %></td>
              <td class="text-center"><%= payment.created_at %></td>
              <!--<td class="text-center"><%= link_to 'Show', payment %></td>-->
              <td class="text-center"><%= link_to 'Editar', edit_payment_path(payment) %></td>
              <td class="text-center"><%= link_to 'Eliminar', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div> 
</section>

app/views/payments/new.html.erb
<%= render 'form', payment: @payment %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<br><br>
<div class="card mx-auto" style="width: 18rem;">
  <div class="card-body head">
    <h5 class="card-title text-white text-center">Detalle del Abono</h5>
  </div>

 <ul class="list-group list-group-flush">
    <li class="list-group-item">Nombre de Cliente: 
      <%= @payment.customer.name %>
    </li>
    <li class="list-group-item">Apellido: 
      <%= @payment.customer.last_name %>
    </li>
    <li class="list-group-item">Saldo Abonado:
       <%= @payment.balance_paid %>
    </li>
    <li class="list-group-item">Fecha:
       <%= @payment.created_at%>
    </li>
  </ul>

<div class="card-body">
  <button id="btn-e"><%= link_to 'Editar', edit_payment_path(@payment), id: "color-b" %></button> 
  <button id="btn-b"><%= link_to 'Regresar', customers_path, id: "color-b" %></button>
</div> 