config/routes.rb
Rails.application.routes.draw do
  get 'balances/index'
  resources :payments, except: %i[ new create]
  resources :products
  resources :customers do 
   resources :loans, only: %i[ new create]
   resources :payments, only: %i[ new create]
  end
 
  resources :loans, except: %i[ new create] do
    collection do  
      get 'form_product', to: 'loans#form_product', as: 'add_products'
    end
  end




  

 
  #Devise 
  devise_for :admins do 
   get '/admins/sign_out', to: 'devise/sessions#destroy', as:'add_logout'
  end 
  authenticate :admin do
   root to: "customers#index"
  end
end


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppRegisterOfLoan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
​
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <!--Fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <!--FontGoogle-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Orelega+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Orelega+One&family=Source+Sans+Pro:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=PT+Serif:ital@1&display=swap" rel="stylesheet">
  </head>
​
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
​
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
      <%= link_to "Registro de clientes", root_path, class: "navbar-brand", id: "clients" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <%= link_to 'Productos', products_path, class: 'nav-link text-white'%>
                </li>
                <li class="nav-item active">
                  <%= link_to 'Préstamos', loans_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item active">
                 <%= link_to 'Abonos', payments_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item active">
                  <%= link_to 'Balances', balances_index_path, class: 'nav-link text-white' %>
                </li>
              </ul>        
              <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                      <%= link_to 'Login', new_admin_session_path, class: 'nav-link text-center text-dark'%>
                        <div class="dropdown-divider"></div>
                        <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'nav-link text-center text-dark'%>
                    </div>
                  </li>
              </ul>
        </div>
    </nav>
​
    <div class='container'>
     <%= yield %>
    </div>   
  
    <footer class= "container-fluid text-center fixed-bottom py-0 my-0">
      <p class="text-white my-0 ">© 2021 Copyright:</p>
      <p class="text-white my-0">La Nueva.Todos los derechos reservados</p>
      </footer> 
  </body> 
</html>  